### ISSUE TITLE
Nargs support

### ISSUE THREAD

**Issue by JasonCust** [ialbert/plac#53]
Is there a way to still support nargs while using plac? I know there is no plan to support it in plac but is there a workaround that can be used?

**Comment by ialbert** [comment]
You can add multiple positional arguments with variable argument definitions:
```

import plac

@plac.pos('words')
def run(*words):
    print(words)
    
if __name__ == '__main__':
    plac.call(run)
```

running it:

```
python code.py one two three
('one', 'two', 'three')
```

**Comment by JasonCust** [comment]
Thanks @ialbert! For this use case, with a little change it would make sense to use positional arguments. Out of curiosity, any suggestions if that were not the case and it made more sense to use an option?

Also, I noticed that the `choices` are no longer enforced with multiple positional arguments:

```import plac

@plac.annotations(
  words = plac.Annotation(
    '',
    'positional',
    None,
    str,
    ['foo', 'bar'],
    metavar = 'WORD'
  ),
  myOption = plac.Annotation(
    '',
    'option',
    'o',
    str,
    metavar = 'OPTION'
  )
)
def run(myOption:str = None, *words):
    print(words, myOption)
    
if __name__ == '__main__':
    plac.call(run)
```

**Comment by ialbert** [comment]
I'd say that an option with multiple arguments looks to be an unusual case, potentially confusing.

As for the choices, indeed it is a small oversight there, choices are not passed to variable arguments, looks like a simple fix, but might take a  bit to get through. Will be noted on this issue.

**Comment by ialbert** [comment]
It turns out that while I can add choice verification it would introduce an incompatibility with prior use. Currently, it is possible to write:

```
import plac

@plac.opt('args', help="Input words", choices=[ "A", "B" ])
@plac.opt('kwds', help="Input key=value pairs", )
def main(*args, **kwds ):
    print(args)
    print(kwds)

if __name__ == '__main__':
    plac.call(main)

```

and use it as:

    program.py A B  x=10  y=20 

and it prints:

```
('A', 'B')
{'x': '10', 'y': '20'}

```

`plac` can parse the command line into variable positional and variable keyword arguments. 

Due to an internal implementation detail, if choices were enforced then the `x=10` would not be valid anymore (initially it is captured as a positional argument) basically the program above would become incorrect. The previously ignored choices would be enforced.

**Comment by JasonCust** [comment]
Thanks for the update @ialbert! Is this a `won't fix` type of issue, or something that will take a bit more thought?

**Comment by ialbert** [comment]
As it turns out there is a "simple" solution that runs the risk of introducing incompatibility. On the other hand, a proper fix looks to be a more complex task.

There should be a tag `takes too much effort`  rather than `won't fix`. We'll wait and see.

**Comment by RuABraun** [comment]
Hi! Thanks for the great package.

It seems it's not possible to both have variable number of arguments while also using options? Can you confirm? Something like:
```
def main(*infs, outf, size: ('', 'option')):
```

**Comment by ialbert** [comment]
You can have a variable number of positional arguments as long as you capture the multiple arguments in last parameter:

```
import plac

@plac.flg('flag')
@plac.opt('opt')
@plac.pos('first')
@plac.pos('rest')
def main(flag, opt, first, *rest):
    print(flag, opt, first, rest)

if __name__ == '__main__':
    plac.call(main)
```

**Comment by RuABraun** [comment]
So I guess there's no way if I do not want to use decorators?

**Comment by ialbert** [comment]
what  I meant is to move the variable argument last like so:

```
def main(size: ('', 'option'), outf, *infs ):
    print(infs, outf, size)


if __name__ == '__main__':
    plac.call(main)

```

**Comment by RuABraun** [comment]
Thank you
