### ISSUE TITLE
Guidance on pluggable subcommands

### ISSUE THREAD

**Issue by JasonCust** [ialbert/plac#54]
Assuming a package with multiple CLIs powered by plac, is there a pattern that is recommended to allow "pluggable" subcommands? In other words, there is an entry point for a package for a CLI command powered by plac, would it be possible to have subcommands from that CLI trigger other CLIs in the package (and then hopefully from other plac CLIs)?

```
mypackage:
 - setup.py (entry point for mycli=mypackage/__main__.py:run)
 - main/
   - __main__.py (plac powered)
   - ...
 - foo/
   - __main__.py (plac powered)
   - ...
 - bar/
   - __main__.py (plac powered)
   - ...
```

All three CLIs could be called independently (`mycli` --> main or `python -m mypackage.main`, and then `python -m mypackage.foo` and `python -m mypackage.bar`)

Execution examples:
`mycli toplevel_command`
`mycli foo [args_for_foo]`
`mycli bar [args_for_foo]`

Ref for a native solution: https://stackoverflow.com/questions/54263164/pluggable-python-sub-command-pattern

**Comment by ialbert** [comment]
I can't comment on the universality of the pattern but I chose  to import the modules dynamically and call the resulting functions via plac like so:

    mod = importlib.import_module(mod_name)
    func = getattr(mod, func_name)
    plac.call(func)

then there is a data structure that maintains the mod_name, func_name values. When using subcommand the main issue usually is how to generate help on each subcommand (without importing/executing the subcommand) amd how to generate help on usage when no parameters are set. For some subcommands not having parameters is an error, for others not. Thus there needs to be a way to trigger the help. 

For an actual implementation see that tackles all the above see:

https://github.com/ialbert/bio/blob/master/biorun/const.py#L27

and

https://github.com/ialbert/bio/blob/master/biorun/main.py#L67

So far this seems to work well and allows me to keep widely different functionalities together.

**Comment by ialbert** [comment]
I have enabled discussions on this project

https://github.com/ialbert/plac/discussions
