### ISSUE TITLE
How can we choose the function to call in the command line? 

### ISSUE THREAD

**Issue by tikitong** [ialbert/plac#60]
First of all, thank you very much for `plac`, it is a very useful tool. 
I would like to know if it is possible to choose the function to call in the command line?
Simply by taking the example of the doc. 

```python
# updatedb.py
import sys
from datetime import datetime

def main(dsn, table='product', today=datetime.today()):
    "Do something on the database"
    print(dsn, table, today)

def main2(dsn, table='product', today=datetime.today()):
    "Do something on the database"
    print(dsn, table, today)

FUNCTION_MAP = {'main' : main, 
                'main2': main2}

if __name__ == '__main__':
    import plac
    plac.call(FUNCTION_MAP[sys.argv[1]])
```
Like this, an error is raised:
`python updatedb.py "main2" hello`
Is there a way?  I don't think I saw an example like this  in the doc. Thank you for your help.

**Comment by ialbert** [comment]
What error are you getting? When I run your example, it works:

    python foo.py "main2" hello

prints:

    main2 hello 2021-08-16 07:41:39.319178

**Comment by tikitong** [comment]
Indeed, my bad, there is no error message but "main2" is affiliated to `dsn` and hello to `product`.  Is there any way to add the function I want to call to the command line?

**Comment by ialbert** [comment]
What you can do is pop the selector  from sys.argv:
```

if __name__ == '__main__':
    import plac
    choice = sys.argv[1]

    sys.argv.remove(choice)

    plac.call(FUNCTION_MAP[choice])
```

**Comment by tikitong** [comment]
Thank you very much, it works well. In general, there is no built-in `plac` method to manage this?

**Comment by ialbert** [comment]
Plac has many features created by the original developer, everything can be done with Plac :-)

I will say that IMHO these look a little complicated for me and I never made use of these. Looks like you can implement subcommand as well:

https://plac.readthedocs.io/en/latest/#implementing-subcommands
