### ISSUE TITLE
How to call an intermediate function which calls project's main?

### ISSUE THREAD

**Issue by mcarans** [ialbert/plac#61]
This looks like a very promising library for simplifying command line argument handling. However I have a use case which may not be handled. I read the documentation but am not sure if it is possible or not.

I was wondering how to go about calling an intermediate function (named facade) in a library that uses some arguments and then passes back to the project's main function?

eg.
```
def main(hdx_site: str = "prod", output_failures: bool = False):
    print(f"I only use output_failures which is {output_failures}")

if __name__ == "__main__":
    plac.call(main)
```

The library has the intermediate function, facade:

```
def facade(projectmainfn: Callable[[Any], None], **kwargs: Any):
    print(f"I do some setup and use hdx_site which is {hdx_site} then I call the project's main")
    projectmainfn(**kwargs)    
```

The plac.call line needs to use main to get the allowed command line arguments, but call facade passing main and the the parsed keyword arguments as parameters to facade. facade does some stuff using some of those arguments then calls main with them (although not all are actually used by main).

Is this possible somehow?

**Comment by ialbert** [comment]
Sorry this is a bit too complicated questions and I will be closing it. 

also it is a question on how to do something in Python and less about issues with the software.
