### ISSUE TITLE
sqlsoup test dependency is unmaintained, doesn't work with SQLAlchemy 1.4.23

### ISSUE THREAD

**Issue by pabs3** [ialbert/plac#62]
The SQLSoup Python module is unmaintained upstream and doesn't work with SQLAlchemy 1.4.23, which Debian has upgraded to, leading to build and CI failures in Debian infrastructure for things that use SQLSoup. The SQLSoup author suggested to switch to the SQLAlchemy automap extension. Since the SQLSoup Python module is only used in plac as an optional test dependency, the Debian package of plac will likely just drop it, but you might want to add support for using the SQLAlchemy automap extension as an alternative to the SQLSoup Python module.

https://bugs.debian.org/995781
https://bugs.debian.org/997325
https://github.com/zzzeek/sqlsoup/issues/1
https://docs.sqlalchemy.org/en/14/orm/extensions/automap.html

**Comment by ialbert** [comment]
thanks for the note, my vote would be to remove that test example, 

even if it is optional we introduce a dependency there that needs to continuously track a much larger and much faster-evolving project.

**Comment by pabs3** [comment]
I'm not familiar with the test and whether or not it is useful, but
removing the test sounds like a reasonable approach.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by micheles** [comment]
Yes, please remove the test.

**Comment by pabs3** [comment]
@ialbert @micheles thanks for confirming. I note the commit missed a few things that [still mention SQLSoup](https://github.com/ialbert/plac/search?q=sqlsoup&type=code):

```
.github/workflows/python-package.yml:        python -m pip install flake8 sqlsoup
.travis.yml:  - pip install sqlsoup
Makefile:       #pip install -q sqlsoup
doc/inactive/dbcli.py:from sqlsoup import SQLSoup
doc/inactive/dbcli.py:    db=plac.Annotation("Connection string", type=SQLSoup),
doc/plac_core.rst:string into a SqlSoup_ object:
doc/plac_core.rst:.. _SqlSoup: http://www.sqlalchemy.org/docs/reference/ext/sqlsoup.html
docs/searchindex.js:Search.setIndex(...sqlsoup:[0,1,2]...}})
```

PS: I suggest deleting most of the contents of the `docs/`, since it all appears to be files generated from the `doc/` directory.
