### ISSUE TITLE
SQLSoup

### ISSUE THREAD

**Issue by pabs3** [ialbert/plac#63]
I note commit be15643 closing #62 missed a few things that still mention SQLSoup:

```
.github/workflows/python-package.yml:        python -m pip install flake8 sqlsoup
.travis.yml:  - pip install sqlsoup
Makefile:       #pip install -q sqlsoup
doc/inactive/dbcli.py:from sqlsoup import SQLSoup
doc/inactive/dbcli.py:    db=plac.Annotation("Connection string", type=SQLSoup),
doc/plac_core.rst:string into a SqlSoup_ object:
doc/plac_core.rst:.. _SqlSoup: http://www.sqlalchemy.org/docs/reference/ext/sqlsoup.html
docs/searchindex.js:Search.setIndex(...sqlsoup:[0,1,2]...}})
```

PS: I suggest deleting most of the contents of the docs/, since it all appears to be files generated from the doc/ directory.

**Comment by ialbert** [comment]
Ok, thanks for following up, this functionality was new for me as well, hence I was quite unfamiliar with all the potential occurrences.  I tried to remove all mentions other than search index, which is probably created with Sphinx.
