### ISSUE TITLE
Python 3.10: asyncore/asynchat are deprecated in favour of asyncio

### ISSUE THREAD

**Issue by pabs3** [ialbert/plac#65]
After merging #64, when running the plac with Python 3.10, there are some deprecation warnings. Since I'm unfamiliar with Python async programming, I won't be able to help fix this (sorry), so I've just filed this issue as a notification.

```
plac_ext.py:806
  plac_ext.py:806: DeprecationWarning: The asyncore module is deprecated. The recommended replacement is asyncio
    import asyncore

plac_ext.py:807
  plac_ext.py:807: DeprecationWarning: The asynchat module is deprecated. The recommended replacement is asyncio
    import asynchat
```

**Comment by ialbert** [comment]
I think it is best if we remove the plac_ext.py from the main source and present it only as example code. Will do this next year.

**Comment by pabs3** [comment]
I'd suggest also removing the asyncore/asynchat use from plac_ext,
once those are removed from the Python standard library.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by musicinmybrain** [comment]
We are encountering this [in Fedora Linux](https://bugzilla.redhat.com/show_bug.cgi?id=2155450) as we begin to test with pre-releases of Python 3.12, in which these deprecated modules are actually removed.

Working around this isn’t as simple as not installing `plac_ext.py`, because both `plac.py` and `plac_tk.py` import from it.

**Comment by musicinmybrain** [comment]
[Patching out the server functionality](https://src.fedoraproject.org/rpms/python-plac/pull-request/1) seems to be an acceptable downstream workaround, but it would be nice if this could be handled upstream before we get we get too close to the [release of Python 3.12](https://peps.python.org/pep-0693/).

**Comment by ialbert** [comment]
I am quite supportive of simplifying and moving that extra functionality into a separate, optional module that would not be explicitly imported into the main package namespace. 

The main blocker would be the original documentation which would need to be modified to the extent of at least mentioning the change.

**Comment by ialbert** [comment]
OK I guess nobody argued for keeping it, so I will be removing the server functionality in the next few days and cut a new release.

**Comment by ialbert** [comment]
dependency on asycnore has been removed, minor version bumped from 1.3 to 1.4


https://github.com/ialbert/plac/commit/af0c125e7e5bfb65f7eb29764a1f407e011a66d9

**Comment by musicinmybrain** [comment]
Looks good to me, and just in time to include the new version in Fedora 39! Thanks.

Would you mind pushing the `v1.4.0` tag to this repository?

**Comment by ialbert** [comment]
tag has been created

https://github.com/ialbert/plac/tree/v1.4.0

**Comment by musicinmybrain** [comment]
> tag has been created

Thanks again!
