### ISSUE TITLE
anomalies in the git repository

### ISSUE THREAD

**Issue by pabs3** [ialbert/plac#66]
@ialbert @micheles I noticed two anomalies in the git repository.

Firstly, there are a lot of [branches](https://github.com/ialbert/plac/branches/all) that look like they should be tags.

```
$ git ls-remote origin | grep refs/heads/[0-9]
e7a54babec6cfbdf51e18de22f95d48e1baac890	refs/heads/0.9.2
0c7ecc497a8886535a4ae1b120bbf33776d35e8e	refs/heads/0.9.3
e814adbbbc982908700f8c00bd295cb186badb2c	refs/heads/0.9.4
46d8d393fbca8820e5cba5d1da808b65a1c879a3	refs/heads/0.9.5
b9dde47eb8f5b70fb6455d20bc146fee01119cf0	refs/heads/0.9.6
fa99e25d997cc5deeab15558b2ff0fa9b736faac	refs/heads/1.0.0
175edc51195cd1c59e299807666b818b4553663b	refs/heads/1.1.0
```

 This set of commands will fix them up (a plac-1.0.0 tag already exists, so I ignored that). You will need to copy-paste all of the `git tag`, `git branch` and `git push` commands to run them.

```
$ git ls-remote origin | sed -n 's_^\(.*\)\srefs/heads/\([0-9].*\)_git tag plac-\2 \1_p' | grep -v plac-1.0.0
git tag plac-0.9.2 e7a54babec6cfbdf51e18de22f95d48e1baac890
git tag plac-0.9.3 0c7ecc497a8886535a4ae1b120bbf33776d35e8e
git tag plac-0.9.4 e814adbbbc982908700f8c00bd295cb186badb2c
git tag plac-0.9.5 46d8d393fbca8820e5cba5d1da808b65a1c879a3
git tag plac-0.9.6 b9dde47eb8f5b70fb6455d20bc146fee01119cf0
git tag plac-1.1.0 175edc51195cd1c59e299807666b818b4553663b
 $ git ls-remote origin | sed -n 's_^\(.*\)\srefs/heads/\([0-9].*\)_git branch -d -r origin/\2 ; git push --delete origin \2_p' 
git branch -d -r origin/0.9.2 ; git push --delete origin 0.9.2
git branch -d -r origin/0.9.3 ; git push --delete origin 0.9.3
git branch -d -r origin/0.9.4 ; git push --delete origin 0.9.4
git branch -d -r origin/0.9.5 ; git push --delete origin 0.9.5
git branch -d -r origin/0.9.6 ; git push --delete origin 0.9.6
git branch -d -r origin/1.0.0 ; git push --delete origin 1.0.0
git branch -d -r origin/1.1.0 ; git push --delete origin 1.1.0
```

Secondly there was an old devel branch whose commits are now hidden because the devel branch is only in GitHub's import namespace and there was some sort of broken merge that split the history in two instead of continuing it.

```
$ git ls-remote origin | grep refs/import/heads/
0b389b1d1a8a3b8c13dc94e082e547f2e33fa830	refs/import/heads/devel
3774fe1847b0e489c1a80590e7bbb8c168845766	refs/import/heads/master
```

Since you probably do not want to rewrite the whole repository to fix this, I suggest using the [git replace](https://git-scm.com/docs/git-replace) feature, which lets you add refs saying that one commit replaces another when viewing the repository. The commands below illustrate downloading the devel commit, finding out the first commit in the master branch, finding the corresponding commit on the devel branch, replacing the first master commit with the corresponding devel commit and then pushing that back to GitHub.

```
$ git fetch origin 0b389b1d1a8a3b8c13dc94e082e547f2e33fa830
$ git log --max-parents=0 HEAD
commit f56c25f54c898366d3437eb19cb654625a93c7d0
Author: Michele Simionato <michele.simionato@gmail.com>
Date:   Mon Apr 23 10:51:05 2012 +0200

    Merged from devel for release 0.9.1
$ git log --oneline 0b389b1d1a8a3b8c13dc94e082e547f2e33fa830 | grep -F 'Merged from devel for release 0.9.1'
f9aeab8 Merged from devel for release 0.9.1
$ git replace f56c25f54c898366d3437eb19cb654625a93c7d0 f9aeab8
$ git push origin 'refs/replace/*:refs/replace/*'
```

**Comment by ialbert** [comment]
@pabs3 what do you think about being a co-developer and you could then perhaps clean that up more efficiently than having to write it all out

**Comment by pabs3** [comment]
My work on plac has been a once-off action mainly to keep it in Debian.
One of the Debian packages my employer uses indirectly depends on plac,
so they care about having it in good enough shape to stay in Debian.
Fixing the Python 3.9/3.10 issues was the main thing that was needed
there, but the values of myself, my employer and Debian encourage
contributing back, so I always try to give back a bit more. That said,
I don't have any personal interest in plac and the package will remain
in Debian so my employer won't want me to join the development team.
So I will have to decline your invitation, thanks for it though.

I tested the instructions on my own fork before posting them so I know
they work and are correct.

If you would like me to join the team for the sole purpose of pushing
the git repository anomaly fixes and would be fine with me leaving
again afterwards, then I don't mind doing that.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by ialbert** [comment]
yes lets do that then, no worries if you leave after

**Comment by pabs3** [comment]
OK, I'm done with the changes to the repository.

I took the liberty of also adding a plac-0.9.1 tag at the last common ancestor on the old part of the split history (which happened to be the right commit too), so that people who don't fetch the `git replace` ref will have access to the latest commits on the old history too.

People who have the repository cloned locally (presumably you both @ialbert @micheles) will need these commands to delete the local tracking branches (origin/1.1.0 etc) for the remote branches that got removed and also to fetch the `git replace` ref that got added.

```
git fetch origin --prune --tags
git fetch origin 'refs/replace/*:refs/replace/*'
```

**Comment by pabs3** [comment]
Thanks for all your work on plac and for helping get all the fixes I proposed merged.

**Comment by pabs3** [comment]
I've successfully removed myself from the repo, so I think this is all done.

Thanks again, and please do run the above commands to sync your local checkouts.

**Comment by ialbert** [comment]
best regards, and cheers. we appreciate the effort to update and clean up the codebase
