### ISSUE TITLE
Can I use clap for tuples or lists arguments?

### ISSUE THREAD

**Issue by lalebarde** [ialbert/plac#68]
Hi, 

I would like to be able to use tuples and lists arguments for my app. Is there a way to do it with clap?

Example : `myapp aaa bbb [cc, ddd, eeee] f (gg, hhh) iii`
--> args = [aaa, bbb, [cc, ddd, eeee], f, (gg, hhh), iii]

**Comment by ialbert** [comment]
there is no support for that behavior,

also do note that you could not even pass parentheses directly as those are shell metacharacters that get interpreted as a new shell, 

you would need to escape those as \(gg hh\)
