### ISSUE TITLE
Recommened method to parse two options that have nargs='+'

### ISSUE THREAD

**Issue by kakila** [ialbert/plac#70]
Consider the function:
```python
def zip_them(x: list(int), y: list(str)):
     return zip(x, y)
```
The desired user interface would be
```bash
myscript_to_zip_them --x 1,2,3 --y a,b,c
```
In the argparser approach one would define x and y as `nargs='+'` with respective types.

If I got it correctly the (impossible) solution with plac would be to define main with the signature
```python
def main(*x, *y):
    ...
```
What is the recommended approach to handle several options that can be lists of a given type, but with undefined number of elements? Can be done with plac?

**Comment by ialbert** [comment]
A  simple solution to this particular problem is to pass a type to the option like so:

```
import plac

def split_int(s):
    return map(int, s.split(','))

def split_str(s):
    return s.split(',')

@plac.opt('x', type=split_int)
@plac.opt('y', type=split_str)
def zip_them(x='1,2,3', y='a,b,c'):
    print(list(zip(x, y)))

if __name__ == '__main__':
    plac.call(zip_them)
```

the function gets applied to each parameter after parsing out the value.

**Comment by kakila** [comment]
Thank you, indeed this solves the problem.

Something to note (my example was not accurate) is that the multiple commands must be separated with a separator **other than** a blank (space). That is, the following **will not** work (would with argparser):
```bash
myscript_to_zip_them --x 1 2 3 --y a b c       # blank separated values
myscript_to_zip_them --x 1, 2, 3 --y a, b, c   # blank after commas
```
as the blanks will cause the values to be parsed as options.

Here is a code snippet with unpaired argument lengths
```python
import plac

def split_int(s):
    return list(map(int, s.split(',')))

def split_str(s):
    return s.split(',')

@plac.opt('x', type=split_int)
@plac.opt('y', type=split_int)
@plac.opt('z', type=split_str)
def options(x=None, y=None, z=None):
    if (y is None) and (z is None):
        parser = plac.parser_from(options)
        parser.print_help()

    print(f'X: {x}\nY: {y}\nZ: {z}')

if __name__ == '__main__':
    plac.call(options)
```

In the example, I added the idea of "you need at least one of them" in the --x and --y options (the script will fail and print the help if both --x and --y options are missing). A suggestion on how to do this the plac way would be very welcomed!

**Comment by ialbert** [comment]
the problem with integrating whitespace as a value separator is that it becomes challenging to use both options and positions arguments. It becomes impossible to tell wether the value `c` in `-x a b c` belongs to the option '-x`  or is an optional positional argument. 

One of the simplest workarounds to add validation that may not be readily available is to look at the `sys.argv` *before* the `plac.call`. To some extent that is another level of command-line parsing, but often far less needs to be done, all you need is to bring `sys.argv` to a valid form. For example write code that turns ['-x', '1', '2', '3'] into ['-x', '1,2,3'] then continue with `plac.call` 

I found that the ability to validate and modify `sys.argv` gave me sufficient utility and was simpler and more generic than coming up with various sophisticated rulesets during parsing.

**Comment by ialbert** [comment]
I will be closing this issue as it is a beyond the scope of the current module.
