### ISSUE TITLE
non-deterministic test failures due to benchmarking in doc/test_runp.py::test3

### ISSUE THREAD

**Issue by pabs3** [ialbert/plac#71]
Forwarding [Debian python-plac#1006999](https://bugs.debian.org/1006999), which was filed by @lamby on behalf of the [Reproducible Builds](https://reproducible-builds.org/) project:

python-plac will randomly fail to build because the testsuite performs
timing/benchmarking. This will vary on (for example) CPU and I/O load.

```
  ____________________________________ test3 _____________________________________
  
      def test3():
          t0 = time.time()
          plac.runp([gen(9), gen(9)])
  >       assert int(time.time() - t0) == 1 # it must take 1 second, not 2
  E       assert 2 == 1
  E         +2
  E         -1
  
  /build/1st/python-plac-1.3.4/.pybuild/cpython3_3.9_plac/build/doc/test_runp.py:26: AssertionError
  =========================== short test summary info ============================
  FAILED doc/test_runp.py::test3 - assert 2 == 1
  ========================= 1 failed, 28 passed in 6.12s =========================

  […]
```

[Full build log](https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/python-plac_1.3.4-1.rbuild.log.gz)

**Comment by pabs3** [comment]
PS: This will cause autoremoval of python-plac from Debian bookworm, so if you fix the issue, please make a new minor release so that it can be added to Debian, preventing the autoremoval.

https://tracker.debian.org/pkg/python-plac

**Comment by ialbert** [comment]
I consider the entire plac_ext.py to be obsolete and unsupported. 

For example, I would drop this test right away. It is not part of plac's main functionality.

**Comment by pabs3** [comment]
Sounds good to me, the test doesn't seem to be that useful anyway.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by micheles** [comment]
I agree, just remove that test.

**Comment by ialbert** [comment]
I have removed the test, bumped the version to 1.3.5

**Comment by pabs3** [comment]
Thanks, will update the Debian package tomorrow.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@ialbert could you add a git tag for the release?

I can't update the Debian package without it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by ialbert** [comment]
@pabs3 added tag v1.3.5

**Comment by pabs3** [comment]
Thanks!

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
