### ISSUE TITLE
Hidden arguments issues

### ISSUE THREAD

**Issue by stefdoerr** [ialbert/plac#73]
Hi, `plac` has some issues when you define hidden function arguments. By convention hidden variables and arguments in python start with underscore. `plac` tries to replace the underscore with a dash, creating a triple-dashed argument. If you have two hidden args it crashes because it tries to create a `-_` short-hand.

```python
@plac.pos("x", "Positional arg x", type=Path)
@plac.opt("_session", argparse.SUPPRESS, type=object)
@plac.opt("_job", argparse.SUPPRESS, type=object)
def main(x, _session=None, _job=None):
    print(locals())
```

```
ArgumentError: argument -_/---job: conflicting option string: -_
```

I'd propose just skipping arguments which start with `_`. I added the following

```python
    def populate_from(self, func):
        [...]
        for name, default in zip(f.args, alldefaults):
            if name.startswith("_"):
                continue
```

This allows me to have hidden arguments which can be used from the python library but not from CLI without having to create yet another function (which is why I use `plac` anyway, to avoid multiple entry points to the same code)

**Comment by ialbert** [comment]
An interesting feature. I would not mind it. Perhaps you could create a pull request for it.

We should also collect additional feedback.
