### ISSUE TITLE
Tests fail on v1.3.5

### ISSUE THREAD

**Issue by winterqt** [ialbert/plac#74]
Python 3.10.6, `python doc/test_plac.py`:

```
AssertionError: usage: example11.py
       [-h]
       i
       n
       [rest ...]

positional arguments:
  i
    This is an
    int
  n
    This is a
    float
  rest
    Other
    arguments

options:
  -h, --help
    show this
    help
    message and
    exit
```

It seems like the text is being wrapped for some reason.

**Comment by ialbert** [comment]
I am going to investigate - in Python 3.10.5 the tests pass, I don't yet have access to to 3.10.6

**Comment by winterqt** [comment]
I can also reproduce this on Python 3.9.13.

**Comment by ialbert** [comment]
On my Mac, it seems to work as expected; what is your OS?

```
$ python -V
Python 3.9.13
```

then 

```
 python doc/test_plac.py
```
prints
```
[...]
Running test_p4
Running test_p5
Running test_sub_help
usage: test_plac.py commit [-h]

options:
  -h, --help  show this help message and exit
Running test_yield
Executed 22 tests OK
```

I believe the default help output is generated/formatted by argparse, though I would have to investigate more, plus I need to be able to reproduce

**Comment by winterqt** [comment]
> On my Mac, it seems to work as expected; what is your OS?

macOS.

Does Plac do anything like reading the terminal width, or rely on any other variable things, that would affect the formatting of the help text?

**Comment by ialbert** [comment]
in general it does very little beyond setting up an argparse instance and populating that, 

argparse comes with Python, perhaps they tweaked something there

I would need to look into how argparse formats help

**Comment by winterqt** [comment]
> Maybe argparse does something like reading the terminal width

It does, see [here](https://github.com/python/cpython/blob/41e8257449c2c44bbe8fc9577cdf5ba0c54b867d/Lib/argparse.py#L170).

**Comment by ialbert** [comment]
well that explains it then, 

in fact, I can now reproduce the error on every Python just by making the terminal smaller. Different tools will fail.

**Comment by winterqt** [comment]
> Different tools will fail depending on the size I drag it to.

Do you mean different tests, or do other tools depend on this and fail?

For plac, I think solution here would be to either hardcode the width parameter (though apparently that shouldn't be used as a stable API, see the comment above the argparse line I posted) and adjust the expected help text accordingly, or maybe just normalizing the amount of spaces when asserting would suffice.

**Comment by ialbert** [comment]
There is a distribution to the widths of different help outputs, so depending on the size, different ones may be affected first.
 
 fixing it seems like a lot of work with not that much benefit;

**Comment by ialbert** [comment]
This seems to be an inconsistency that comes from the argparse module that plac relies on hence we can't fix it.
