### ISSUE TITLE
can't import `Interpreter`

### ISSUE THREAD

**Issue by ricehornet** [ialbert/plac#77]
Hello,

I've just installed the latest release (1.4.0) and found that I can't import `Interpreter`:

```
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import plac
>>> plac.Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'plac' has no attribute 'Interpreter'
>>> dir(plac)
['Annotation', 'ArgumentParser', 'Monitor', 'NONE', 'PARSER_CFG', 'ReadlineInput', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'annotations', 'argparse', 'call', 'date', 'datetime', 'default_help', 'flg', 'functools', 'getargspec', 'getfullargspec', 'import_main', 'inspect', 'is_annotation', 'iterable', 'opt', 'parser_from', 'pconf', 'pos', 're', 'stdout', 'sys', 'textwrap', 'time', 'to_date', 'to_datetime', 'version']
>>> import plac_ext
>>> plac_ext.Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'plac_ext' has no attribute 'Interpreter'
>>> dir(plac_ext)
['BaseTask', 'HelpSummary', 'MPTask', 'Manager', 'Monitor', 'PLACDIRS', 'PlacFormatter', 'Process', 'ReadlineInput', 'StartStopObject', 'SynTask', 'TaskManager', 'TerminatedProcess', 'ThreadedTask', '_', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'argparse', 'attrgetter', 'cmd', 'contextmanager', 'decode', 'default_help', 'exec_', 'format_help', 'gen_exc', 'gen_val', 'import_main', 'importlib', 'inspect', 'itertools', 'less', 'load_source', 'multiprocessing', 'nulltask', 'os', 'partial_call', 'plac_core', 'raise_', 'raw_input', 'read_line', 'read_long_line', 'sharedattr', 'shlex', 'signal', 'stdout', 'subprocess', 'sys', 'terminatedProcess', 'threading', 'traceback', 'use_less', 'version', 'with_statement', 'write']
```

I suspect that it's due to [this change](https://github.com/ialbert/plac/commit/af0c125e7e5bfb65f7eb29764a1f407e011a66d9#diff-b55f1f4934b1ef89cdefffbd53899c9e944ad742e6081226e02e02ba40707c11L29) which removed the `Interpreter` import from the main `plac` module. Could this have been accidentally removed with the server features? Or am I doing something wrong?

Thanks!

**Comment by ialbert** [comment]
Yes, correct, that section of the code became unusable in Python 3.12 due to the deprecation in Python of the asyncore/asynchat packages.

Plac to version 1.3.5 the last version that has the Interpreter so I would suggest pinning to that version.

**Comment by ialbert** [comment]
We should probably raise an exception with an error message when importing that module to inform users of the workaround.

**Comment by daniel-davee** [comment]
Could you please document the workaround for this? I use Interpreter in most of my projects.

**Comment by ialbert** [comment]
load a previous version of plac < 1.4, or better yet add the previous version of plac to your code, so it does not depend on it

the problem is caused by Python 3.12 removing specific libraries from the standard module

**Comment by daniel-davee** [comment]
So does that mean plac can't do subcommands any more? I'm asking because
I'm a tool works like Django but for cli projects. I'm also writing CLI and
I just wanted way to have it setup a plac project real quick, but it
heavily relies on this feature.
Thank you
Daniel Davee

**Comment by ialbert** [comment]
actually, now that I looked it more closely, we did not need to remove the Interpreter from the import just because we removed asyncore dependency, that was an oversight on my part,

the Interpreter ought to work just

I have made a new release see if that works for you, if so 1.4.0 will be removed and 1.4.1 should be the new default

**Comment by daniel-davee** [comment]
Thank you so much. This helps a lot.

**Comment by musicinmybrain** [comment]
> I have made a new release see if that works for you, if so 1.4.0 will be removed and 1.4.1 should be the new default

Would you mind pushing the `v1.4.1` git tag? Thanks!

**Comment by ialbert** [comment]
tagged

**Comment by musicinmybrain** [comment]
> tagged

Thank you!

**Comment by ricehornet** [comment]
Awesome, I also thought that it didn't have to be removed with asyncore. Thank you -- closing.
