### ISSUE TITLE
Tests fail starting with Python 3.13.0a4 due to changes in help text output format

### ISSUE THREAD

**Issue by musicinmybrain** [ialbert/plac#80]
```
$ python3.13 -V
Python 3.13.0a4
$ python3.13 -m venv _e
$ . _e/bin/activate
(_e) $ pip install -e .
(_e) $ python docs/test_plac.py
```

```
Running test_cmd_abbrevs
usage: test_plac.py {help,commit} ...
test_plac.py: error: No command 'foo'
Running test_cmds
Running test_date_default
Running test_doctest
Running test_expected_help
Traceback (most recent call last):
  File "/home/ben/src/forks/plac/doc/test_plac.py", line 353, in <module>
    maybegen = test()
               ~~~~^^
  File "/home/ben/src/forks/plac/doc/test_plac.py", line 85, in test_expected_help
    check_help(fname[:-5])
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/home/ben/src/forks/plac/doc/test_plac.py", line 73, in check_help
    assert got == expected, got
           ^^^^^^^^^^^^^^^
AssertionError: usage: example13.py [-h] [-l] [-y] [-s 100]

options:
  -h, --help     show this help message and exit
  -l, --list
  -y, --yield    [False]
  -s, --sys 100  [100]
```

I plan to open a PR to document all the changes to `.help` files needed for these tests to pass on Python 3.13.0a4, but it will unconditional and therefore for documentation (and downstream patching purposes) only; I’m sure you will want to somehow conditionalize these tests to preserve compatibility with both Python 3.12 and older and Python 3.13 and newer.

**Comment by ialbert** [comment]
what is the change in the format? I suppose some sort of whitespace formatting is different?

I was wondering if it were better to remove the whitespace or split by words and compare the word content rather than the exact formatting. In the end the tool generates its output via the argparse help which, if changes is solely a Python issue.

**Comment by ialbert** [comment]
thanks for the help there, 

it looks like the changes are more substantial and we need to carry another batch of output files for 3.13 and up

**Comment by ialbert** [comment]
I have made some changes, and the tests now pass. 
 
 Python 3.13 and above plac uses different files as the expected outputs.
 
 Could you test branch `py313` to see whether that also fixes the problem on your side?
 
 https://github.com/ialbert/plac/tree/py313

**Comment by musicinmybrain** [comment]
It looks like fixing up “today” isn’t working correctly on Python 3.13:

```
3.13/example5
usage: example5.py [-h] dsn [table] [today]

Do something on the database

positional arguments:
  dsn
  table       [product]
  today       [2024-02-21]

options:
  -h, --help  show this help message and exit
Traceback (most recent call last):
  File "/builddir/build/BUILD/plac-03b7fd200e26f421de6a1e077577a4a6b1aa7fac/doc/test_plac.py", line 373, in <module>
    maybegen = test()
               ~~~~^^
  File "/builddir/build/BUILD/plac-03b7fd200e26f421de6a1e077577a4a6b1aa7fac/doc/test_plac.py", line 105, in test_expected_help
    check_help(fname[:-5])
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/builddir/build/BUILD/plac-03b7fd200e26f421de6a1e077577a4a6b1aa7fac/doc/test_plac.py", line 93, in check_help
    assert got == expected, diff
           ^^^^^^^^^^^^^^^
AssertionError: ---

+++

@@ -5,7 +5,7 @@

 positional arguments:
   dsn
   table       [product]
-  today       [2024-02-20]
+  today       [2024-02-21]

 options:
   -h, --help  show this help message and exit
```

**Comment by musicinmybrain** [comment]
> It looks like fixing up “today” isn’t working correctly on Python 3.13:
> 
> […]

(This is reproducible in a virtualenv now that the date has rolled over.)

**Comment by ialbert** [comment]
indeed, I have now added a fix for that as well.

**Comment by musicinmybrain** [comment]
> indeed, I have now added a fix for that as well.

Thanks! Looks like https://github.com/ialbert/plac/tree/py313 now works for me on both Python 3.12.2 and 3.13.0a4.

**Comment by ialbert** [comment]
A new release has been made public version 1.4.3 to incorporate the changes, also tagged as v1.4.3

**Comment by musicinmybrain** [comment]
Works perfectly! Thanks.
