### ISSUE TITLE
[Documentation] Should the first Quickstart example work?

### ISSUE THREAD

**Issue by josh-hadley** [ialbert/plac#83]
For the first [**Quickstart**](https://github.com/ialbert/plac?tab=readme-ov-file#quickstart) example:
```python
import plac

def main(model, iter=100, debug=False):
    """
    A script for machine learning
    """
    print (model, iter, debug)

if __name__ == '__main__':
    # Execute function via plac.call()
    plac.call(main)
```

The documentation suggests that the above program can take parameters from the command line like:
`% python example.py -d -i 1000 B`

but running that produces an error:
```
% python example.py -d -i 1000 B
usage: example.py [-h] model [iter] [debug]
example.py: error: argument iter: invalid int value: 'B'
```
I did some additional tinkering and it looks like using param labels (abbrevs like `-d` or full form like `--debug`) doesn't work in this mode where plac infers params from the function signature alone (without decorators).

The program _does_ run without error if you drop the labels and supply params in positional order, like:
`% python example.py B 1000 True`
or
`% python example.py X`

This infer-params-from-function-signature may be something that used to work and got broken, or maybe the docs have been wrong all along. I'm happy to supply a documentation update if it's the latter.

P.S. Just noticed that the expected output for running the program with no params is also wrong. The docs say it should produce this output:
```
usage: example.py [-h] [-i 100] [-d] {A,B,C}
example.py: error: the following arguments are required: model
```
but it actually produces this:
```
% python example.py
usage: example.py [-h] model [iter] [debug]
example.py: error: the following arguments are required: model
```

**Comment by ialbert** [comment]
Sorry about that; one of the pitfalls of copy-pasting outputs rather than executing the code.

In this case the output of another, later example was copied over by accident.

**Comment by josh-hadley** [comment]
No worries, I suspect that use case isn't too common anyway but I was preparing a mini-tutorial on plac and noticed the discrepancy while testing. Thanks so much for your speedy attention to this! I really, really love plac!

**Comment by michael-lachmann** [comment]
Hi, the page on https://pypi.org/project/plac/ still has this same problem.

BTW: how come this doesn't work? Why do you need to specify `@plac.opt()` for the abbreviations to work? Why not just take the definition from the function definition?

**Comment by ialbert** [comment]
I did not push out a new version just because the README was updated - but maybe I should have. Now I realize the PyPI docs are pulled from that readme. I'm kind of uneasy about pushing out a new software version to fix just that.

**Comment by ialbert** [comment]
I made a new release that now contains the corrected readme on PyPI as well.
